@startwbs
* Step Mount
** set install root to /{uuid} inside config
** for each ${partition} in ${storage.devices[*].partitions}
*** set ${partition.InstallMount} to ${installRoot + partition.Mount}
*** mount ${partition.Device} ${partition.InstallMount}
@endwbs
